services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: api/app.py
    command: flask run --host=0.0.0.0
