services:
  ramayanam-kg:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/kg/statistics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/app/data
      - ./api:/app/api
      - ./scripts:/app/scripts