version: '3.8'

services:
  # Flask API Server (for development with external React dev server)
  ramayanam-api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5000
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from volume mount
      - /app/ui/node_modules  # Exclude node_modules from volume mount
    command: ["python", "-c", "from api.app import app; app.run(host='0.0.0.0', port=5000, debug=True)"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/ramayanam/kandas/1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # React Dev Server
  ramayanam-ui:
    image: node:18-alpine
    working_dir: /app/ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    environment:
      - NODE_ENV=development
    depends_on:
      - ramayanam-api